# Generated by Django 4.2.3 on 2023-07-13 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='upvote',
        ),
        migrations.AddField(
            model_name='topic',
            name='users_downvote',
            field=models.ManyToManyField(related_name='users_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='users_upvote',
            field=models.ManyToManyField(related_name='users_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
