# Generated by Django 4.2.3 on 2023-07-12 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars/', validators=[django.core.validators.validate_image_file_extension, django.core.validators.FileExtensionValidator(['JPEG', 'JPG', 'PNG'])]),
        ),
    ]
